# Generated by Django 3.1.1 on 2020-09-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslistcloneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
